### ISSUE TITLE
Error: no gitconfig to be found at <directory>

### ISSUE THREAD

**Issue by ramseycc** [RichardLitt/watch-gh-repos#17]
Getting the following error when running from command line. I have a .gitconfig file in the directory specified.

"Error: no gitconfig to be found at <directory>"

**Comment by RichardLitt** [comment]
Do you have a .git folder? This is likely a problem with my implementation of the gitconfiglocal package.

**Comment by ramseycc** [comment]
I do not. I was also trying this implementation on Windows 10.

**Comment by RichardLitt** [comment]
I pushed a commit which should make the help text clearer. Let me know if it works for you now.
